/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.

*/

/**
 *
 * @author PRANSHU
 */
package phonebook;

import java.sql.DriverManager;
import java.sql.ResultSet;
import com.mysql.jdbc.Connection;
import com.mysql.jdbc.Statement;
import java.sql.*;

import javax.swing.JOptionPane;



public class phonebook extends javax.swing.JFrame {
    
    //these variables are the data members of the class phonebook.they can be accessed and used in fucntion of the class
    String pid;
    int Mobile,LandLine;
    String Name,DateOfBirth,OfficeAddress,HomeAddress,Email;
    
    Connection con;
    Statement stmt;
    ResultSet rs;
    
    String query,query2,query3,query4,query5; 
    // this function is called the default contructor of the class phonebook.we write the connection code in the contructor
    

    /**
     * Creates new form phonebook
     */
    public phonebook() {
        initComponents();
        
        try{
        
         Class.forName("java.sql.DriverManager");
        
         con= (Connection) DriverManager.getConnection("jdbc:mysql://localhost:3306/school","root","root");
        
         stmt = (Statement) con.createStatement();
        
        query="select * from phonebook";
        
        rs= stmt.executeQuery(query);
        
        /* move to the record and if succesful, then take out the data from the result set 
        and display it in the textfields using getData() and showData()
        */
        if (rs.next())
        {
        
        getData();
        showData();
        
        }
        
        }
        
        
        catch(Exception e)
        {
        
        JOptionPane.showMessageDialog(null,e.getMessage());
        } //end of contructor 
        
        //fucntion to retrievethe data from the resultset object and store it in variables
         void getData()
        {
        try {
        
        //taking the data from the resultset and store it in a variable
        
        Name=rs.getString(1);
        DateOfBirth=rs.getString(2);
        OfficeAddress=rs.getString(3);
        HomeAddress=rs.getString(4);
        Email=rs.getString(5);
        LandLine=rs.getInt(6);
        Mobile=rs.getInt(7);
        pid=rs.getString(8);
        
        
        
        
        }
        catch(Exception e)
        {
        
        JOptionPane.showMessageDialog(null,e.getMessage());
        }
        }
        //end of get data function
        
        //function to display the data (that we retrieved from the result set and stored in varisable) 
        //in the textfields 
        
        void showData()
        
        {
        //taking the data from the variables and putting in the textfields 
            
            jTextField1.setText(Name);
            jTextField2.setText(DateOfBirth);
            jTextField3.setText(OfficeAddress);
            jTextField4.setText(HomeAddress);
            jTextField5.setText(Email);
            jTextField6.setText(Integer.toString(LandLine));
             jTextField7.setText(Integer.toString(Mobile));
             jTextField8.setText(pid);
            
        
        
        
        
        }
       
        
        
       
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jButton7 = new javax.swing.JButton();
        jTextField2 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jTextField4 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jTextField5 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jTextField6 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jTextField7 = new javax.swing.JTextField();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jTextField8 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButton1.setText("ADD");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("EDIT");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("FIRST ");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setText("PREVIOUS");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton5.setText("DELETE ");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jButton6.setText("CLEAR THE FIELDS");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jLabel1.setText("NAME");

        jButton7.setText("EXIT");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        jLabel2.setText("DATE OF BIRTH");

        jLabel3.setText("OFFICE ADDRESS");

        jLabel4.setText("HOME ADDRESS");

        jLabel5.setText("EMAIL");

        jLabel6.setText("LANDLINE");

        jLabel7.setText("MOBILE");

        jButton8.setText("LAST");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });

        jButton9.setText("NEXT");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });

        jButton10.setText("SEARCH");
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });

        jLabel8.setText("PERSONAL.ID");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton7)
                        .addGap(25, 25, 25))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel1)
                                            .addComponent(jLabel2)
                                            .addComponent(jLabel3))
                                        .addGap(28, 28, 28)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(jTextField2, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
                                            .addComponent(jTextField1)
                                            .addComponent(jTextField3)))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel4)
                                            .addComponent(jLabel5)
                                            .addComponent(jLabel6))
                                        .addGap(36, 36, 36)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jTextField7)
                                            .addComponent(jTextField4)
                                            .addComponent(jTextField5)
                                            .addComponent(jTextField6))))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(133, 133, 133)
                                        .addComponent(jLabel8)
                                        .addGap(68, 68, 68)
                                        .addComponent(jTextField8, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jButton3))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addGap(569, 569, 569)
                                        .addComponent(jButton4)
                                        .addGap(0, 0, Short.MAX_VALUE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jButton6)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jButton1)
                                                .addGap(41, 41, 41)
                                                .addComponent(jButton2)
                                                .addGap(36, 36, 36)
                                                .addComponent(jButton10)
                                                .addGap(112, 112, 112))
                                            .addComponent(jButton8)
                                            .addComponent(jButton9)))))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jButton5)))
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton3)
                    .addComponent(jLabel8)
                    .addComponent(jTextField8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addComponent(jButton8)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel3)
                            .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(33, 33, 33)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(64, 64, 64)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jButton2)
                                .addComponent(jButton1)
                                .addComponent(jButton10))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 47, Short.MAX_VALUE))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton4)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton9)
                            .addGap(18, 18, 18))))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jButton5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton6))
                .addGap(42, 42, 42)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton7)
                    .addComponent(jLabel7)
                    .addComponent(jTextField7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        try {
        
            rs.first();
            getData();
            showData();
                
                   }
        
        
         catch(Exception e)
        { 
         JOptionPane.showMessageDialog(this,e.getMessage());
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:
       JOptionPane.showMessageDialog(null,"THANKS FOR VISITING");
      System.exit(0);
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
        jTextField1.setText("");
        jTextField2.setText("");
        jTextField3.setText("");
        jTextField4.setText("");
        jTextField5.setText("");
        jTextField6.setText("");
        jTextField7.setText("");
        jTextField8.setText("");
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        try {
            

         
             
        Class.forName("java.sql.DriverManager");
        
         con= (Connection) DriverManager.getConnection("jdbc:mysql://localhost:3306/school","root","root");
        
         stmt = (Statement) con.createStatement();
        
        //validating the data
        
        if(jTextField1.getText().isEmpty())
        {
        
        JOptionPane.showMessageDialog(null,"Please Enter your Name");
        jTextField1.grabFocus();
        
        return;
                              
        }
        
        else {
        
        Name=jTextField1.getText();
        
        }
        
         if(jTextField2.getText().isEmpty())
        {
        
        JOptionPane.showMessageDialog(null,"Please Enter your Date Of Birth");
        jTextField2.grabFocus();
        
        return;
                              
        }
        
        else {
        
        DateOfBirth=jTextField2.getText();
        
        }
        
         if(jTextField3.getText().isEmpty())
        {
        
        JOptionPane.showMessageDialog(null,"Please Enter your Office Address");
        jTextField3.grabFocus();
        
        return;
                              
        }
        
        else {
        
        OfficeAddress=jTextField3.getText();
        
        }
        
         if(jTextField4.getText().isEmpty())
        {
        
        JOptionPane.showMessageDialog(null,"Please Enter your Home Address");
        jTextField4.grabFocus();
        
        return;
                              
        }
        
        else {
        
       HomeAddress= jTextField4.getText();
        
        }
        
          if(jTextField5.getText().isEmpty())
        {
        
        JOptionPane.showMessageDialog(null,"Please Enter your Email");
        jTextField5.grabFocus();
        
        return;
                              
        }
        
        else {
        
        Email=jTextField5.getText();
        
        }
         
          if(jTextField6.getText().isEmpty())
        {
        
        JOptionPane.showMessageDialog(null,"Please Enter your Mobile Number");
        jTextField6.grabFocus();
        
        return;
                              
        }
        
        else {
        
        LandLine=Integer.parseInt(jTextField6.getText());
        
        }
          
          if(jTextField7.getText().isEmpty())
        {
        
        JOptionPane.showMessageDialog(null,"Please Enter your Mobile Number");
        jTextField7.grabFocus();
        
        return;
                              
        }
        
        else {
        
        Mobile=Integer.parseInt(jTextField7.getText());
        
        }
          
           if(jTextField8.getText().isEmpty())
        {
        
        JOptionPane.showMessageDialog(null,"Please Enter your Desired Personal Id");
        jTextField8.grabFocus();
        
        return;
                              
        }
        
        else {
        
        pid=jTextField8.getText();
        
        }
         
         query3= "Insert into phonebook values('"+pid+"','"+Name+"','"+DateOfBirth+"','"+OfficeAddress+"','"+HomeAddress+"','"+Email+"',"+LandLine+","+Mobile+");";    
                                                             
         stmt.executeUpdate(query3);
         
        }      
        catch(Exception e)
        { 
         JOptionPane.showMessageDialog(this,e.getMessage());
        }
        
        
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
         try {
        
            rs.previous();
            getData();
            showData();
                
                   }
        
        
         catch(Exception e)
        { 
         JOptionPane.showMessageDialog(this,e.getMessage());
        }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        // TODO add your handling code here:
         try {
        
            rs.last();
            getData();
            showData();
                
                   }
        
        
         catch(Exception e)
        { 
         JOptionPane.showMessageDialog(this,e.getMessage());
        }
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        // TODO add your handling code here:
        try{
        
        rs.next();
        getData();
        showData();
        
        
        
        }
        
        catch(Exception e)
        {
        
        JOptionPane.showMessageDialog(null,e.getMessage());
        
        }
    }//GEN-LAST:event_jButton9ActionPerformed

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
        // TODO add your handling code here:
        
        try {
        
        
        Class.forName("java.sql.DriverManager");
        
        
        con= (Connection) DriverManager.getConnection("jdbc:mysql://localhost:3306/School","root","root");
        
        stmt=(Statement) con.createStatement();
        
        pid=jTextField8.getText();
        
        query2= "select * from phonebook where personId = '"+ pid +"';";
        
        rs=stmt.executeQuery(query2);
        
        if(rs.next())
        {
        Name=rs.getString(1);
        DateOfBirth=rs.getString(2);
        OfficeAddress=rs.getString(3);
        HomeAddress=rs.getString(4);
        Email=rs.getString(5);
        LandLine=rs.getInt(6);
        Mobile=rs.getInt(7);
        pid=rs.getString(8);
        
        
        
        
        jTextField1.setText(Name);
            jTextField2.setText(DateOfBirth);
            jTextField3.setText(OfficeAddress);
            jTextField4.setText(HomeAddress);
            jTextField5.setText(Email);
            jTextField6.setText(Integer.toString(LandLine));
             jTextField7.setText(Integer.toString(Mobile));
        jTextField8.setText(pid);
        
        
        }
        else{
        
        JOptionPane.showMessageDialog(null,"There is no record for this Personal ID");
        
        }
        
        }
          catch(Exception e)
        { 
         JOptionPane.showMessageDialog(this,e.getMessage());
        }
        //end of search button code
    }//GEN-LAST:event_jButton10ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        
            

        try{
             
        Class.forName("java.sql.DriverManager");
        
         con= (Connection) DriverManager.getConnection("jdbc:mysql://localhost:3306/school","root","root");
        
         stmt = (Statement) con.createStatement();
        
        //validating the data
        
        if(jTextField1.getText().isEmpty())
        {
        
        JOptionPane.showMessageDialog(null,"Please Enter your Name");
        jTextField1.grabFocus();
        
        return;
                              
        }
        
        else {
        
        Name=jTextField1.getText();
        
        }
        
         if(jTextField2.getText().isEmpty())
        {
        
        JOptionPane.showMessageDialog(null,"Please Enter your Date Of Birth");
        jTextField2.grabFocus();
        
        return;
                              
        }
        
        else {
        
        DateOfBirth=jTextField2.getText();
        
        }
        
         if(jTextField3.getText().isEmpty())
        {
        
        JOptionPane.showMessageDialog(null,"Please Enter your Office Address");
        jTextField3.grabFocus();
        
        return;
                              
        }
        
        else {
        
        OfficeAddress=jTextField3.getText();
        
        }
        
         if(jTextField4.getText().isEmpty())
        {
        
        JOptionPane.showMessageDialog(null,"Please Enter your Home Address");
        jTextField4.grabFocus();
        
        return;
                              
        }
        
        else {
        
       HomeAddress= jTextField4.getText();
        
        }
        
          if(jTextField5.getText().isEmpty())
        {
        
        JOptionPane.showMessageDialog(null,"Please Enter your Email");
        jTextField5.grabFocus();
        
        return;
                              
        }
        
        else {
        
        Email=jTextField5.getText();
        
        }
          
          
          if(jTextField6.getText().isEmpty())
        {
        
        JOptionPane.showMessageDialog(null,"Please Enter your Mobile Number");
        jTextField6.grabFocus();
        
        return;
                              
        }
        
        else {
        
        LandLine=Integer.parseInt(jTextField6.getText());
        
        }
          
         
          if(jTextField7.getText().isEmpty())
        {
        
        JOptionPane.showMessageDialog(null,"Please Enter your Mobile Number");
        jTextField7.grabFocus();
        
        return;
                              
        }
        
        else {
        
        Mobile=Integer.parseInt(jTextField7.getText());
        
        }
          
           if(jTextField8.getText().isEmpty())
        {
        
        JOptionPane.showMessageDialog(null,"Please Enter your Desired Personal Id");
        jTextField8.grabFocus();
        
        return;
                              
        }
        
        
        else {
        
        pid=jTextField8.getText();
        
        }
           
        
        
        query4="UPDATE PHONEBOOK SET NAME='"+Name+"',DateOfBirth='"+DateOfBirth+"',AddressOffice='"+OfficeAddress+"',Email='"+Email+"',LandLine="+LandLine+",Mobile='"+Mobile+"'WHERE PersonId='"+pid+"';";                 
           
        
        stmt.executeUpdate(query4);
                
                
        }   
            catch(Exception e)
        { 
         JOptionPane.showMessageDialog(this,e.getMessage());
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        
        
 try{
        
         Class.forName("java.sql.DriverManager");
        
         con= (Connection) DriverManager.getConnection("jdbc:mysql://localhost:3306/school","root","root");
        
         stmt = (Statement) con.createStatement();
         
         pid=jTextField8.getText();
         
         query5="DELETE FROM PHONEBOOK WHERE PersonId='"+pid+"';";
         
         
         stmt.executeUpdate(query5);        
                 
                 
                                                                                                                                                                                                                     
                             }
 
 
 
                    catch(Exception e)
        { 
         JOptionPane.showMessageDialog(this,e.getMessage());
        }
    }//GEN-LAST:event_jButton5ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(phonebook.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(phonebook.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(phonebook.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(phonebook.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new phonebook().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField8;
    // End of variables declaration//GEN-END:variables
}
